### ISSUE TITLE
Scripted sequences and scripted sentences don't play nicely together 

### ISSUE THREAD

**Issue by TheBoxTrot** [shishkabob27/hls2#12]
It seems most of the time the scripted sequence will play with the Audio scripted sentences but no mouth sync and in rare cases it will do the lip syncing but not play animations 
Is this due to the fact that scripted sequences override the animgraph???

**Comment by Xenthio** [comment]
facepunch/sbox-issues#2182 
mouths are done in the animgraph so yeah until i can directly playback and control a node in the graph i can't do much without making everything messier than it already is
