### ISSUE TITLE
Infinite Recursive Loop

### ISSUE THREAD

**Issue by gidgeesheep** [shishkabob27/hls2#20]
An infinite recursive loop prints out out a single letter 'p' into the console. This happens immediately on load.

![sbox_0013](https://user-images.githubusercontent.com/55063683/194943843-23774119-87d0-44f2-8e67-0b2b477c2c19.jpg)

**Comment by Xenthio** [comment]
hmm, thats odd, doesnt seem to happen for me

**Comment by Xenthio** [comment]
can you click on it in the tools mode and see the stacktrace so i can find where it is in the code?

**Comment by gidgeesheep** [comment]
After restarting S&box, the problem seems to have been resolved. Sorry, I can't replicate it.

**Comment by Xenthio** [comment]
all good, probably means it was solved in the last or so update :P
