### ISSUE TITLE
Suggestions -- needed tools

### ISSUE THREAD

**Issue by Babyherc1001** [shishkabob27/hls2#3]
stuff that i need and stuff i like to suggest

replace sounds with orignal step sounds, wood, AND metal, and general concrete.

Better Scripted sequences to were a animation can stay on hold if requested to. and when a trigger is triggered and the trigger is connected to the scripted sequences. the animation plays and pauses on the last frame of the animation

add zombie and vortigaunt entities for the chapters they appear in, epesally vortigaunt to finish office_complex. 

(kinda unsure about this)
add NPC shootable boxes so guns can actualy hit the npc

**Comment by Xenthio** [comment]
Surfaces flesh and default have been added, default being the only with footsteps right now,
scripted sequences animations work but I've commented them all out as they're shit and I can't do what I want to do until facepunch/sbox-issues#2182 is solved. 
progress is slow and steady but getting somewhere

**Comment by Xenthio** [comment]
zombie and vortigaunt to be done and is my next thing,

**Comment by Xenthio** [comment]
zombie and vort stubs added.

**Comment by Xenthio** [comment]
scripted sequence animations match original more now.

**Comment by Xenthio** [comment]
these should basically all be done now, i think!
