### ISSUE TITLE
Map propertie on whether the player can recruit allies + propertie on certain entities 

### ISSUE THREAD

**Issue by TheBoxTrot** [shishkabob27/hls2#9]
currently, the player can click on any old scientist and recruit him. this is fine in later levels but for the intro levels the player shouldn't be able to do this. as it can screw with their sequences. if we have a map property to check whether the player is allowed to recruit or not we can stop that from happening globally per map and even active it or disable it with hammer IO, we should also add one to the entity so that if we have an entity we don't want to be recruited we can set it but if map property is set to no then it overrides the entities bool
(note don't think face punch has given us the ability to create map properties but they will eventually)

**Comment by shishkabob27** [comment]
If the flag "PreDisaster" is enabled, then the NPC will not follow the player.
